version: '3.8'
services:
  frontend:
    build:
      context: ./Client/client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://superemiliano:1234@localhost:27017/spotify?authSource=admin
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
